### ISSUE TITLE
Status console client crashes

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-console-client#91]
I am currently using latest master commit and client crashes when started, see error below:

```
Starting in /tmp/status-term-client/047c40140d1de5ad77e72f57fb6b8529ad74e51b
Contact address: 0x047c40140d1de5ad77e72f57fb6b8529ad74e51b8dfe5ca579a3229f0ccfd175bfcb96f3da6a4905a020ebeccbe5936e0cd65b6f16f026f650483ae64e6e1297b7
panic: invalid argument to Intn

goroutine 48 [running]:
math/rand.(*Rand).Intn(0xc0000b42a0, 0x0, 0xc000269980)
        /home/dd/.go/src/math/rand/rand.go:169 +0x9c
math/rand.Intn(...)
        /home/dd/.go/src/math/rand/rand.go:329
github.com/status-im/status-console-client/protocol/transport.randomItem(...)
        /home/dd/status/src/github.com/status-im/status-console-client/protocol/transport/utils.go:7
github.com/status-im/status-console-client/protocol/transport.(*WhisperServiceTransport).selectAndAddMailServer(0xc0000ce730, 0x100, 0x7f2064e0efff, 0x400, 0x7f2064c35c00)
        /home/dd/status/src/github.com/status-im/status-console-client/protocol/transport/whisper_service.go:188 +0x71
github.com/status-im/status-console-client/protocol/transport.(*WhisperServiceTransport).Request(0xc0000ce730, 0x159c6c0, 0xc0000c6030, 0x2246148, 0x0, 0x0, 0x125bf41, 0x14, 0x3e8, 0x5d075833, ...)
        /home/dd/status/src/github.com/status-im/status-console-client/protocol/transport/whisper_service.go:164 +0x43
github.com/status-im/status-console-client/protocol/adapter.(*ProtocolWhisperAdapter).Request(0xc0001292e0, 0x159c6c0, 0xc0000c6030, 0xc0011d0180, 0x2, 0x2, 0x3e8, 0x5d075833, 0x5d08a9b3, 0x2, ...)
        /home/dd/status/src/github.com/status-im/status-console-client/protocol/adapter/protocol_whisper.go:151 +0x14f
github.com/status-im/status-console-client/protocol/client.(*Messenger).requestHistories(0xc0000ce780, 0x159c6c0, 0xc0000c6030, 0xc000297480, 0x2, 0x2, 0xc0011d0180, 0x2, 0x2, 0x3e8, ...)
        /home/dd/status/src/github.com/status-im/status-console-client/protocol/client/messenger.go:168 +0x1b3
github.com/status-im/status-console-client/protocol/client.(*Messenger).RequestAll.func2(0xc000091920, 0xc0000ce780, 0x159c6c0, 0xc0000c6030, 0xc000297480, 0x2, 0x2, 0xbf3a484cdca50f3c, 0x16e40a0e, 0x22176c0, ...)
        /home/dd/status/src/github.com/status-im/status-console-client/protocol/client/messenger.go:204 +0x121
created by github.com/status-im/status-console-client/protocol/client.(*Messenger).RequestAll
        /home/dd/status/src/github.com/status-im/status-console-client/protocol/client/messenger.go:203 +0x302```

**Comment by dshulyak** [comment]
@adambabik could be it be related to recent refactoring?
